### ISSUE TITLE
New Installation of 1.0.1 on HA 2024.1.0: Please wait, starting configuration wizard for miner then 500 Internal Server Error

### ISSUE THREAD

**Issue by Dukat-Gul** [Schnitzel/hass-miner#280]
## Version of the custom_component
Having some errors with the new version.

```
Installed version
v1.0.1
Latest version
v1.0.1
```

Brand new fresh installation of Home Assistant 
```
Core
2024.1.0
Frontend
20240103.3
```
HACS first thing I installed before any Discovered Integrations.
```
Home Assistant Community Store 
Integration version: 1.33.0
Frontend version: 20230406083157
```

I have since installed another HACS repo and it is working as expected.

## Describe the bug

Once the miner repo is added to HACS and I try to launch it 

The immediate box displayed is
`Please wait, starting configuration wizard for miner`
and then a minute or so later:
`Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble
`

I have restarted HA, 
I have also tried re-downloading the 1.0.1 repo and HA restarting.
Lastly I tried downgrading to 1.0.0 and after a HA restart 
Finally - removed HA 2024.1.0 and then installed HA 2023.12.3 and retried.

**Comment by UpstreamData** [comment]
Can you check your logs?  My guess is they'll say something like:

```Cannot install package pyasic, as it has conflicting dependencies```

If not, can you send them here?

**Comment by philtechsl** [comment]
Hi, I have the same issue. I tried almost same steps and I always get the reply:

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble.

**Comment by UpstreamData** [comment]
We're working on getting my PR merged which should fix this I believe, maybe you guys want to test on my branch and see if it fixes the issue so we can confirm?

https://github.com/UpstreamData/hass-miner

**Comment by philtechsl** [comment]
> We're working on getting my PR merged which should fix this I believe, maybe you guys want to test on my branch and see if it fixes the issue so we can confirm?
> 
> https://github.com/UpstreamData/hass-miner

I tested and have the same problem:

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble.

**Comment by UpstreamData** [comment]
Ok.  Are you able to send logs here?  If you don't want to send them here, you can send them to me on telegram, username is b_rowan.

**Comment by philtechsl** [comment]
File "/usr/src/homeassistant/homeassistant/requirements.py", line 290, in _async_process_requirements

    raise RequirementsNotFound(name, list(failures))

homeassistant.requirements.RequirementsNotFound: Requirements for miner not found: ['pyasic==0.40.3'].

2024-01-04 23:27:57.122 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:27:57.126 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration solarweb which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:27:57.130 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration miner which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:27:57.137 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration fronius_inverter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:27:57.142 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:27:57.145 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:27:57.149 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:27:57.154 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration config_editor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:27:57.157 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration solarman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

[22:28:46] INFO: Home Assistant Core finish process exit code 100

2024-01-04 23:28:50.351 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:28:50.351 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration solarweb which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:28:50.352 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration miner which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:28:50.352 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration fronius_inverter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:28:50.352 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:28:50.354 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:28:50.355 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:28:50.357 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration config_editor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:28:50.359 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration solarman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-01-04 23:29:19.132 ERROR (MainThread) [frontend.js.latest.202306080] http://192.168.1.48:8123/config/integrations/dashboard:0:0 ResizeObserver loop completed with undelivered notifications.

2024-01-04 23:29:46.136 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package pyasic==0.40.3: ERROR: Cannot install pyasic==0.40.3 because these package versions have conflicting dependencies.

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts



[notice] A new release of pip is available: 23.1.2 -> 23.3.2

[notice] To update, run: pip install --upgrade pip

2024-01-04 23:30:09.255 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package pyasic==0.40.3: ERROR: Cannot install pyasic==0.40.3 because these package versions have conflicting dependencies.

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts



[notice] A new release of pip is available: 23.1.2 -> 23.3.2

[notice] To update, run: pip install --upgrade pip

2024-01-04 23:30:32.425 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package pyasic==0.40.3: ERROR: Cannot install pyasic==0.40.3 because these package versions have conflicting dependencies.

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts



[notice] A new release of pip is available: 23.1.2 -> 23.3.2

[notice] To update, run: pip install --upgrade pip

2024-01-04 23:30:32.430 ERROR (MainThread) [aiohttp.server] Error handling request

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request

    resp = await request_handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle

    resp = await handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl

    return await handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware

    return await handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware

    return await handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware

    return await handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware

    return await handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware

    return await handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle

    result = await handler(request, **request.match_info)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 149, in post

    return await super().post(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper

    result = await method(view, request, data, *args, **kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post

    result = await self._flow_mgr.async_init(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 845, in async_init

    flow, result = await task

                   ^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 863, in _async_init

    flow = await self.async_create_flow(handler, context=context, data=data)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 962, in async_create_flow

    await _load_integration(self.hass, handler_key, self._hass_config)

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2026, in _load_integration

    await async_process_deps_reqs(hass, hass_config, integration)

  File "/usr/src/homeassistant/homeassistant/setup.py", line 418, in async_process_deps_reqs

    await requirements.async_get_integration_with_requirements(

  File "/usr/src/homeassistant/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements

    return await manager.async_get_integration_with_requirements(domain)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements

    await self._async_process_integration(integration, done)

  File "/usr/src/homeassistant/homeassistant/requirements.py", line 186, in _async_process_integration

    await self.async_process_requirements(

  File "/usr/src/homeassistant/homeassistant/requirements.py", line 252, in async_process_requirements

    await self._async_process_requirements(name, missing)

  File "/usr/src/homeassistant/homeassistant/requirements.py", line 290, in _async_process_requirements

    raise RequirementsNotFound(name, list(failures))

homeassistant.requirements.RequirementsNotFound: Requirements for miner not found: ['pyasic==0.40.3'].

**Comment by UpstreamData** [comment]
Ok, this is the problem I expected.  You may need to go into ssh, go to the custom components folder, and `rm hass-miner`, then re-install it from my branch.  It's still trying to install pyasic==0.40.3, which is from this repository, not the updated version I have.

**Comment by philtechsl** [comment]
> Ok, this is the problem I expected. You may need to go into ssh, go to the custom components folder, and `rm hass-miner`, then re-install it from my branch. It's still trying to install pyasic==0.40.3, which is from this repository, not the updated version I have.

I don´t really know how to get to the "custom components folder". I am a bit newb with HA an raspberry PI.

Thanks

**Comment by UpstreamData** [comment]
You will have to go into the SSH plugin, once there you can type `ls` to see directories, `cd <directory>` to move to it, you're looking for `custom_components`, once you see that type `cd custom_components`, `rm -r hass-miner`, that should remove it, then you can remove it in the HACS interface and re-add it from my repo.

**Comment by philtechsl** [comment]
Hi I did manage to remove miner custom_componets folder. I added your repo but still same problem. See the log:


2024-01-05 01:08:15.434 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:15.443 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration solarweb which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:15.445 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration miner which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:15.447 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration fronius_inverter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:15.449 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:15.451 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:15.453 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:15.455 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration config_editor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:15.457 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration solarman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:45.339 WARNING (MainThread) [homeassistant.core] Task <Task pending name='Task-2589' coro=<Scanner._ssdp_listener_process_with_lookup() running at /usr/src/homeassistant/homeassistant/components/ssdp/__init__.py:481> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown
2024-01-05 01:08:45.352 WARNING (MainThread) [homeassistant.core] Task <Task pending name='Task-2587' coro=<Scanner._ssdp_listener_process_with_lookup() running at /usr/src/homeassistant/homeassistant/components/ssdp/__init__.py:481> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown
2024-01-05 01:08:45.354 WARNING (MainThread) [homeassistant.core] Task <Task pending name='Task-2588' coro=<Scanner._ssdp_listener_process_with_lookup() running at /usr/src/homeassistant/homeassistant/components/ssdp/__init__.py:481> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown
[00:08:46] INFO: Home Assistant Core finish process exit code 100
2024-01-05 01:08:51.005 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:51.006 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration solarweb which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:51.008 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration miner which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:51.009 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration fronius_inverter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:51.011 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:51.012 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:51.013 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:51.015 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration config_editor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:08:51.016 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration solarman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-05 01:09:34.801 ERROR (MainThread) [frontend.js.latest.202306080] http://192.168.1.48:8123/config/integrations/dashboard:0:0 ResizeObserver loop completed with undelivered notifications.
2024-01-05 01:10:03.393 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package pyasic==0.45.0: ERROR: Cannot install pyasic==0.45.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
2024-01-05 01:10:27.060 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package pyasic==0.45.0: ERROR: Cannot install pyasic==0.45.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
2024-01-05 01:10:50.598 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package pyasic==0.45.0: ERROR: Cannot install pyasic==0.45.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
2024-01-05 01:10:50.601 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 149, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 845, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 863, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 962, in async_create_flow
    await _load_integration(self.hass, handler_key, self._hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2026, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 418, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 186, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 252, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 290, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for miner not found: ['pyasic==0.45.0'].

**Comment by UpstreamData** [comment]
I'm going to start testing on my own HASS instance here soon, can you confirm you're on HASS 2024.1.0?

**Comment by philtechsl** [comment]
> I'm going to start testing on my own HASS instance here soon, can you confirm you're on HASS 2024.1.0?

I am on 2023.6.3. I will update it and try tomorrow again. Perhaps that is the problem. I didn’t know about the new release.

thanks

**Comment by schwoi** [comment]
@UpstreamData I have just installed a fresh HA on a RPi4 running your repo and get the config come up no worries however trying to add the miners gets "Unable to authenticate with Miner, is Username & Password correct?" even with the correct details supplied.

![image](https://github.com/Schnitzel/hass-miner/assets/7381086/fe615014-1661-4bda-a9bb-5cf7c3a8578d)

There are 2 errors logged.

This error originated from a custom integration.

Logger: custom_components.miner.config_flow
Source: custom_components/miner/config_flow.py:43
Integration: Miner (documentation, issues)
First occurred: 13:32:39 (6 occurrences)
Last logged: 13:33:10

Miner setup error: 'NoneType' object has no attribute 'get'



Logger: py.warnings
Source: runner.py:188
First occurred: 13:32:45 (3 occurrences)
Last logged: 13:33:39

/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py:352: RuntimeWarning: coroutine 'sleep' was never awaited self._tasks: set[asyncio.Task] = set()
/usr/local/lib/python3.11/site-packages/httpcore/_models.py:80: RuntimeWarning: coroutine 'sleep' was never awaited (
/usr/local/lib/python3.11/asyncio/events.py:80: RuntimeWarning: coroutine 'sleep' was never awaited self._context.run(self._callback, *self._args)

**Comment by UpstreamData** [comment]
@schwoi Can you confirm the miner type?  This still won't work with any IceRiver stuff, that is WIP, but if this is like and S19 or something, then there may be an issue.

If it's supported by pyasic (https://pyasic.readthedocs.io/en/latest/miners/supported_types/), try setting the repo version to `v0.0.1-rc.1` and re-trying with that.  I remove the try except that was catching that error, so it will give a full traceback now, as whatever it was passing back before was stunningly unhelpful.

**Comment by schwoi** [comment]
This is for an Antminer S19 and S9

**Comment by schwoi** [comment]
@UpstreamData running v0.0.1-rc.1 i get Unknown error occurred

![image](https://github.com/Schnitzel/hass-miner/assets/7381086/6d596df6-efb2-4b47-ac8d-f091af6a1030)


Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 14:40:11 (1 occurrences)
Last logged: 14:40:11

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 323, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 419, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miner/config_flow.py", line 76, in async_step_user
    errors = await validate_input(user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miner/config_flow.py", line 39, in validate_input
    await miner.get_data(include=["mac"])
  File "/usr/local/lib/python3.11/site-packages/pyasic/miners/base.py", line 582, in get_data
    gathered_data = await self._get_data(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/miners/base.py", line 518, in _get_data
    web_command_data = await web_command_task
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/bosminer/__init__.py", line 99, in multicommand
    gql_data = await self.gql.multicommand(*gql_commands)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/bosminer/__init__.py", line 137, in multicommand
    data = await self.send_command(command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/bosminer/__init__.py", line 159, in send_command
    if command.get("query") is None:
       ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by UpstreamData** [comment]
@schwoi I think I fixed it.  Issue with pyasic, for some reason it was sending an empty graphql command string and failing.  Should be working now back on the main branch.

**Comment by schwoi** [comment]
Yep, can confirm it works.

**Comment by Dukat-Gul** [comment]
Thanks @schwoi & @UpstreamData 
I can also confirm working using main branch of https://github.com/UpstreamData/hass-miner on HA 2024.1.0

**Comment by Sjors** [comment]
I'm still getting a `pyasic` error. I run Home Assistant OS in a VM, updated today:

<img width="614" alt="Scherm­afbeelding 2024-01-06 om 12 04 39" src="https://github.com/Schnitzel/hass-miner/assets/10217/3a509ca7-3f7d-4ebc-97de-4bed178ee8c9">


```
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 10:51:14 AM (1 occurrences)
Last logged: 10:51:14 AM

Setup failed for custom integration 'miner': Requirements for miner not found: ['pyasic==0.40.3'].
```

**Comment by grolub** [comment]
After updating home assistant core to v. 2024.1.2 the integration stopped working. I get this error message after restart as a notification:

Logger: homeassistant.setup
Source: setup.py:221
First occurred: 17:23:08 (1 occurrences)
Last logged: 17:23:08

Setup failed for custom integration 'miner': Requirements for miner not found: ['pyasic==0.40.3'].

**Comment by grolub** [comment]
> @grolub the issue is that they updated HTTPX in the new version of home assistant, but older pyasic versions aren't compatible with the newer version. The new version of pyasic is compatible though, that's what PR #252 is for.
> 
> Until that gets merged, you can use my fork, https://github.com/upstreamdata/hass-miner

I deleted all existing custom component files and tried installing your fork. Got this error message:

Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by UpstreamData** [comment]
Interesting.  Beta 1.1.0 just got released here with the fix, maybe give that a shot.  HASS must be on 2024.1.0 or greater, but from testing on my instance it was working good.  Does take a while to load the first time though while it installs all the packages.

**Comment by Sjors** [comment]
I successfully switched to v1.1.0-beta2. Fan speed also still works (#275).

**Comment by Moonraker-007** [comment]
Many thanks for your work !!
For me it´s the first time posting something here, I hope Iám doing right.
My HA Version is know 2024 1.5

installing your Repository HAS is telling me "you will find it in '/config/custom_components/miner'"
in my HAS Terminal & ssh i do find the folder "config" and also "homeassistant" in both folder i find "customs_components" and "miner" not "hss-miner". If i delete your repository via Hacs, the "miner" Folder are gone. After new install i do have the "Error500" problem again. 
I cannot find "hss-miner"? 

LOG 

Error handling request
17:13:24 – (FEHLER) /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py
Unable to install package pyasic==0.40.3: ERROR: Cannot install pyasic==0.40.3 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
17:13:24 – (FEHLER) util/package.py - Die Nachricht ist zum ersten Mal am 17:13:09 aufgetreten und erscheint 3 malcd

any idea turning of that 0.40.3

many many thanks

Carsten from Muenster Germany

**Comment by UpstreamData** [comment]
Hey Carsten, make sure to enable beta versions with the switch on configuration, then you should be able to either select `master` or `[v1.1.0-beta2](https://github.com/Schnitzel/hass-miner/releases/tag/v1.1.0-beta2)`, that should fix it.

**Comment by Moonraker-007** [comment]
very cool it ist running, fastest  support ever :-)

**Comment by b-rowan** [comment]
Pushed out a new release, v1.1.0, should fix this issue.  Going to close this as it has gotten kindof off topic now.
