### ISSUE TITLE
Failing to setup new miner that is running BraiinsOS (previously working)

### ISSUE THREAD

**Issue by timothy-p-h** [Schnitzel/hass-miner#476]
Hello,

Its seems something has become broken (at least for me) since yesterday. Prior to yeseterday, I did have 1x succesful miner configured and working in HA using the hass-miner integration. However, I went to add a 2nd miner, and it kept coming up with the following error. I then removed my old miner and tried re-adding that one, and it comes up with the same error:

![image](https://github.com/user-attachments/assets/6f152949-3377-4980-b69f-c173c6d7e232)

These outputs are in the logs:

**AssertionError
2025-01-15 15:55:27.747 ERROR (MainThread) [custom_components.miner.coordinator] Failed to call config on S19j Pro (BOS+): 192.168.50.57 while getting data.
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyasic/miners/base.py", line 525, in _get_data
    miner_data[data_name] = await function(**args_to_send)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyasic/miners/backends/braiins_os.py", line 800, in get_config
    return MinerConfig.from_boser(grpc_conf)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyasic/config/__init__.py", line 232, in from_boser
    mining_mode=MiningModeConfig.from_boser(grpc_miner_conf),
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyasic/config/mining/__init__.py", line 630, in from_boser
    scaling=ScalingConfig.from_boser(grpc_miner_conf, mode="power"),
            ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyasic/config/mining/scaling.py", line 111, in from_boser
    return cls._from_boser_power(grpc_miner_conf)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyasic/config/mining/scaling.py", line 131, in _from_boser_power
    return cls(**conf)
  File "/usr/local/lib/python3.13/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ScalingConfig
shutdown
  Input should be a valid dictionary or instance of ScalingShutdown [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type**


I have also attached the log file.
[error_log (4).txt](https://github.com/user-attachments/files/18420390/error_log.4.txt)

Not sure if I am doing something wrong or if something has changed? My miners are running BraiinsOS - and I can connect to them via HTTP/webpage without any issue. It seems just to be the HA integration that has stopped.

**Comment by 86codyharris** [comment]
i had the same issue pop up with no changes on my side.  2 of my miners have stopped responding, one is still functional

**Comment by timothy-p-h** [comment]
Okay - I think the issue is caused by the "Dynamic Performance Scaling" feature in Braiins. It seems that when that is enabled, the configuration is failing to parse when trying to add the device. As soon as I disable that option, the mining devices could be succesfully re-added.

**Comment by b-rowan** [comment]
It's actually failing to parse because the default value is being used for the shutdown modes, and so in the case that it is turned on and the shutdown is on default settings it will fail.  I just need to change the type of the value in the config and it should be fine.

**Comment by timothy-p-h** [comment]
Awesome. Thanks @b-rowan

**Comment by b-rowan** [comment]
I think it should be fixed in 1.1.23, try that?  Fixed the type hints in pyasic...

**Comment by timothy-p-h** [comment]
Thanks!
I was able to add the devices (in v 1.1.23) as long as the "Shutdown When Minimal Power Target Is Reached" option is selected. 

![image](https://github.com/user-attachments/assets/8d8764cc-a316-44e8-bf31-276b48a0b5f4)

If you leave this option un-selected (which is the default when you enable Dynmaic Performance Scaling) it still fails to add. I have attached the logs below for when trying to add the miner with this option unselected.

[error_log (5).txt](https://github.com/user-attachments/files/18434134/error_log.5.txt)

Thanks again!

**Comment by 86codyharris** [comment]
I've updated to Hass-miner to 1.1.23 and updated HACs and HA to current versions. Everything working great!

**Comment by Tanki90** [comment]
i have the same issue with 1.1.26

**Comment by b-rowan** [comment]
It's failing to parse the config, I'm not exactly sure what is causing that to fail to parse, but if anyone with that issue can send over the contents of `/etc/bosminer.toml` that would help (`cat /etc/bosminer.toml`)

**Comment by Tanki90** [comment]
root@miner-9fc4db:~# cat /etc/bosminer.toml
[format]
version = '2.0'
model = 'Antminer S9'
generator = 'BOSer (boser-openwrt 0.1.0-26ba61b9)'
timestamp = 1738335794

[temp_control]
target_temp = 80.0
hot_temp = 90.0
dangerous_temp = 100.0

[fan_control]
min_fans = 2

[[group]]
name = 'Default'
quota = 1

[[group.pool]]
enabled = false
url = 'stratum2+tcp://v2.stratum.slushpool.com/u95GEReVMjK6k5YqiSFNqqTnKU4ypU2Wm8awa6tmbmDmk1bWt'
user = '!non-existent-user!'
password = ''

[[group.pool]]
enabled = false
url = 'stratum+tcp://stratum.slushpool.com:3333'
user = '!non-existent-user!'
password = ''

[[group.pool]]
enabled = true
url = 'stratum2+tcp://v2.eu.stratum.braiins.com/u95GEReVMjK6k5YqiSFNqqTnKU4ypU2Wm8awa6tmbmDmk1bWt'
user = 'xxxx.s9antminer'
password = 'xxxxx'

[[group.pool]]
enabled = false
url = 'stratum+tcp://sha256asicboost.auto.nicehash.com:9200'
user = 'NHbMAme2pUEvCULVtLyjRYBE9dCJfu6oi5cs.s9antminer'
password = 'x'

[autotuning]
enabled = true
power_target = 650

[performance_scaling]
enabled = false
shutdown_enabled = false

**Comment by b-rowan** [comment]
Your miner needs an update, that's an older version of the config.  You will need to update to 22.08.1.  You can do this by SSHing into the miner, then running `wget -O /tmp/firmware.tar https://feeds.braiins-os.com/am1-s9/firmware_2022-09-27-0-26ba61b9-22.08.1-plus_arm_cortex-a9_neon.tar && sysupgrade /tmp/firmware.tar`

**Comment by Tanki90** [comment]
Thx that was the Problem!
